name: Trigger cleanup after merge

permissions:
  contents: write

on:
  pull_request:
    types: [closed]
    branches:
      - 'release/*'

jobs:
  trigger-cleanup:
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check branch and trigger CircleCI
        env:
          CIRCLECI_API_TOKEN: ${{ secrets.CIRCLECI_API_TOKEN }}
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
          REPO_NAME: aviv_platform_classifieds_import
        run: |
          # Check if it's a feature/bugfix/hotfix branch
          if [[ "$BRANCH_NAME" =~ ^(feature|hotfix|bugfix|bug|feat)\/.* ]]; then
            echo "Triggering cleanup for branch $BRANCH_NAME"
            BRANCH_WITHOUT_PREFIX=$(echo "$DELETED_BRANCH" | sed -E 's/^(feature|hotfix|bugfix|bug|feat)\///')
          
            # Debugging: Print the value of BRANCH_WITHOUT_PREFIX
            echo "BRANCH_WITHOUT_PREFIX: $BRANCH_WITHOUT_PREFIX"
            
            # Trigger CircleCI workflow with repo details
            curl -X POST https://circleci.com/api/v2/project/github/$REPO_NAME/pipeline \
              -H "Circle-Token: $CIRCLECI_API_TOKEN" \
              -H "Content-Type: application/json" \
              -d '{
                "branch":"main",
                "parameters":{
                  "cleanup":true,
                  "ticket_id":"'"$BRANCH_WITHOUT_PREFIX"'",
                  "repo":"'"$REPO_NAME"'"
                }
              }'
              
            echo "CircleCI cleanup job triggered for $BRANCH_WITHOUT_PREFIX"
          else
            echo "Not triggering cleanup for $BRANCH_NAME as it doesn't match our pattern"
          fi
        shell: /usr/bin/bash -e {0}