name: Delete branch after merge

permissions:
  contents: write

on:
  pull_request:
    types: [closed]
    branches:
      - 'release/*'

jobs:
  delete-merged-branch:
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Delete merged branch
        uses: SvanBoxel/delete-merged-branch@main
        with:
          github_token: ${{ github.token }}
          branch_pattern: 'feature/*, bugfix/*, hotfix/*, bug/*, feat/*'
