name: Delete branch after merge

permissions:
  contents: write

on:
  pull_request:
    types: [closed]
    branches:
      - 'release/*'

jobs:
  delete-merged-branch:
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Delete merged branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: |
          # Check if it's a feature/bugfix/hotfix branch
          if [[ "$BRANCH_NAME" =~ ^(feature|hotfix|bugfix|bug|feat)\/.* ]]; then
            echo "Deleting branch $BRANCH_NAME"
            gh repo view "${{ github.repository }}" # Just to verify we can access the repo
            gh api -X DELETE "repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME" || echo "Failed to delete remote branch $BRANCH_NAME"
          else
            echo "Not deleting branch $BRANCH_NAME as it doesn't match our pattern"
          fi
        shell: /usr/bin/bash -e {0}
